# Generated by Django 5.1.4 on 2024-12-12 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('price', models.IntegerField()),
                ('user', models.ManyToManyField(related_name='book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
