# Generated by Django 5.1.4 on 2024-12-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookmodel_category'),
        ('categories', '0003_rename_categories_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='categories.categorie'),
        ),
    ]
