# Generated by Django 5.1.4 on 2024-12-14 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_bookmodel_category_bookmodel_category'),
        ('categories', '0003_rename_categories_categorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='category',
            field=models.ManyToManyField(blank=True, to='categories.categorie'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
