# Generated by Django 5.1.4 on 2024-12-15 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_user_comment_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='des',
            new_name='description',
        ),
    ]
